apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
  labels:
    name: reverseproxy
    stack: books
spec:
  type: LoadBalancer
  selector:
    name: reverseproxy
  ports:
   - port: 80
     targetPort: 8080
     protocol: TCP
