service: download-service

custom:
  bucket: books-downloads

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2
  stackTags:
    app: books
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  download:
    handler: books.download
    events:
      - http:
          path: /download
          method: get
    environment:
      BOOKS_BUCKET: ${self:custom.bucket}
      JWT_SECRET: "I've got a lovely bunch of coconuts"
    # Misc 
    tags:
      app: books